### ISSUE TITLE
When installed on new freePBX-16 system and activated, the system cannot do a reload anymore

### ISSUE THREAD

**Issue by charles-darwin** [POSSA/freepbx-Outbound_CNAM#11]
The Outbound-CNAM module (if installed and activated) needs at least one outbound-route (and a trunk) in freePBX, otherwise the system cannot reload anymore.
When you do a fwconsole reload you get this:
[root@freepbx ~]# fwconsole reload --verbose
Reload Started

In extensions.class.php line 197:
                                         
  [Exception]                            
  died in splice macro-dialout-trunk  s  
                                         

Exception trace:
  at /var/www/html/admin/libraries/extensions.class.php:197
 extensions->splice() at /var/www/html/admin/modules/outcnam/Outcnam.class.php:111
 FreePBX\modules\Outcnam->doDialplanHook() at /var/www/html/admin/libraries/BMO/DialplanHooks.class.php:107
 FreePBX\DialplanHooks->processHooks() at /var/www/html/admin/libraries/Console/Reload.class.php:318
 FreePBX\Console\Command\Reload->reload() at /var/www/html/admin/libraries/Console/Reload.class.php:91
 FreePBX\Console\Command\Reload->execute() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:992
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/lib/asterisk/bin/fwconsole:163

reload [--json] [--dry-run] [--skip-registry-checks] [--dont-reload-asterisk
![outbound-cnam](https://user-images.githubusercontent.com/8002658/155861621-14fd054d-f78e-4bb5-a431-8642e3d2d29e.png)
]

**Comment by lgaetz** [comment]
I have a fix for this issue committed here:
https://github.com/lgaetz/freepbx-Outbound_CNAM/blob/master/Outcnam.class.php

Can someone test and confirm it's working as expected before I merge?

**Comment by lgaetz** [comment]
Resolved in ver 0.0.6 now available for install from http://pbxossa.org/files/outcnam/
